name: Coding Conventions

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-style:
    name: Run Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php --allow-risky=yes --dry-run -v

  phpstan:
    name: "Run Static Analysis: PHPStan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: vendor/bin/phpstan --error-format=github

#  rector:
#    name: "Run Static Analysis: Rector"
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.2
#          coverage: none
#
#      - name: Install composer dependencies
#        uses: ramsey/composer-install@v3
#
#      - name: Run Rector
#        run: vendor/bin/rector process --no-ansi --dry-run --no-progress-bar
